// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbvpLeV2pLy2k_28mJ_vCXc2hJq2yG9s',
    appId: '1:1074492897883:web:45349adadc4c45c5619d7e',
    messagingSenderId: '1074492897883',
    projectId: 'agrirent-2c230',
    authDomain: 'agrirent-2c230.firebaseapp.com',
    storageBucket: 'agrirent-2c230.firebasestorage.app',
    measurementId: 'G-V2N8VH1SZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LjJv5QviTn5R3151XHGhIXVeNKMaZy4',
    appId: '1:1074492897883:android:79cd2eff47896d12619d7e',
    messagingSenderId: '1074492897883',
    projectId: 'agrirent-2c230',
    storageBucket: 'agrirent-2c230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU3etMyp0irzM03Usa6FqkYx_iuisGCS8',
    appId: '1:1074492897883:ios:5d0da5b7e44c7df8619d7e',
    messagingSenderId: '1074492897883',
    projectId: 'agrirent-2c230',
    storageBucket: 'agrirent-2c230.firebasestorage.app',
    iosBundleId: 'com.example.agrirent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU3etMyp0irzM03Usa6FqkYx_iuisGCS8',
    appId: '1:1074492897883:ios:5d0da5b7e44c7df8619d7e',
    messagingSenderId: '1074492897883',
    projectId: 'agrirent-2c230',
    storageBucket: 'agrirent-2c230.firebasestorage.app',
    iosBundleId: 'com.example.agrirent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPbvpLeV2pLy2k_28mJ_vCXc2hJq2yG9s',
    appId: '1:1074492897883:web:f022f384e19a9d24619d7e',
    messagingSenderId: '1074492897883',
    projectId: 'agrirent-2c230',
    authDomain: 'agrirent-2c230.firebaseapp.com',
    storageBucket: 'agrirent-2c230.firebasestorage.app',
    measurementId: 'G-3J8JKEKQ8L',
  );
}
